version: '3.1'

services:
  app:
    container_name: rules_bot
    build:
      dockerfile: Dockerfile.prod
      context: .
    restart: unless-stopped
    env_file: .env
    expose: 
      - 3000
    environment:
      VIRTUAL_HOST: rules.vgrong.com
      LETSENCRYPT_HOST: rules.vgrong.com
    networks:
      - global
      - proxy

networks:
  global:
    external:
      name: global
  proxy:
    external:
      name: proxy
