version: '3.1'

services:

  app:
    container_name: rules_bot
    build:
      context: .
    # restart: "always"
    volumes:
      - ./src:/app/src
    depends_on: 
      - db
    env_file: .env
    expose: 
      - 3000
    environment:
      VIRTUAL_HOST: rules.dev.vgrong.com
      LETSENCRYPT_HOST: rules.dev.vgrong.com

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rules_dev
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
